workspace = {}

[package]
name = "todomvc"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.27.0"
strum_macros = "0.27.0"
serde = "1.0.200"
serde_derive = "1.0.200"
yew = {version = "0.21.0", features = ["web_sys"]}
